# Generated by Django 5.0.6 on 2024-06-28 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_cartoes', '0002_categoria_remove_gasto_cartao_alter_gasto_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='cartao',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='gestao_cartoes.cartao'),
            preserve_default=False,
        ),
    ]
