# Generated by Django 5.0.6 on 2024-06-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_cartoes', '0003_gasto_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='vencimento',
            field=models.IntegerField(),
        ),
    ]
