# Generated by Django 5.0.6 on 2024-06-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_cartoes', '0004_alter_cartao_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='parcelas',
            field=models.IntegerField(default=1),
        ),
    ]
