# Generated by Django 5.0.6 on 2024-06-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_cartoes', '0006_cartao_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='imagem',
            field=models.ImageField(default='imagens_cartoes/default_image.jpg', upload_to='imagens_cartoes/'),
        ),
    ]
