# Generated by Django 5.0.6 on 2024-07-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_cartoes', '0007_alter_cartao_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
