# Generated by Django 5.0.6 on 2024-11-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_cartoes', '0010_cartao_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='pago',
        ),
    ]
